name: tweetbot

on:
  schedule:
    - cron: '15 15 * * *'

jobs:
  tweetbot-post:
    runs-on: macOS-latest
    env:
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      MEANINGCLOUD_TOKEN: ${{ secrets.MEANING_TOKEN }}
      ENDPOINT_TOKEN: ${{ secrets.ENDPOINT_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e 'install.packages(c("rtweet", "dplyr", "curl", "jsonlite", "remotes", "DBI", "RSQLite"))'
      - name: Install GitHub packages
        run: Rscript -e 'remotes::install_github("ropensci/rtweet")'
      - name: Download data
        run: Rscript tweets_action.R
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
